### ISSUE TITLE
Create API Documentation

### ISSUE THREAD

**Issue by inezchong7** [UoaWDCC/passport#106]
## Description

As a future executive of WDCC
I want to have access to documentation for this project
So that I can better understand the codebase for maintenance and improvements

## Acceptance Criteria

- [x] Delete commented out code.  

For Api.ts: 
- [x] Provide a brief overview of what this file does (e.g., manages API routes for various operations).
- [x] Document any middleware or external libraries used in the file (e.g., express, multer).

For image.ts:
- [x] Add an introductory comment explaining this file handles image uploads for events, including its interaction with AWS S3 for storage.
- [x] Clarify how the multer library is used for handling file uploads, and explain the S3 client setup and usage.

For prize.ts:
- [x] Provide a high-level overview of the purpose of this file (e.g., handling prize creation, retrieval, and updates).
- [x] For each route, add comments explaining the HTTP method, route parameters, expected inputs/outputs, and common error cases.

For user.ts:
- [x] Explain any interactions between the User and Prize models, as well as external dependencies like the totalStampsCalc pipeline.

**Comment by derogative404** [comment]
complete
