### ISSUE TITLE
Prizes Admin Dashboard

### ISSUE THREAD

**Issue by derogative404** [UoaWDCC/passport#27]
## Description

As a admin
I want to view the names of the students that have achieved a prize. Once they have collected their prize, I would like to check off their name and it should disappear from the dashboard.

## Proposed Solution

[https://www.figma.com/file/tvnkfOcsSfp21oouz9Lbqy/Initial-Design?type=design&node-id=1%3A2&mode=design&t=wjUjqygQIxZS5Kkj-1](url)

## Acceptance Criteria

- [x] Utilises `/dashboard/prizes` route
- [x] Prizes table created as per schema. Connected by userID
- [ ] Table like format, with the column headings being "Name" (student's firstname and lastname) and "Prize Received" (checkbox when student has received a prize)
- [ ] "Name" column displays the name of the student
- [x] "Prize Received" column displays a checkbox
- [x] Once a checkbox under "Prize Received" is checked for an associated student, the row containing the student's name and checkbox should disappear on the frontend but remains on the back end.

**Comment by BW82262** [comment]
This is basically done without the first and last names in the table, idk why it's not working

**Comment by derogative404** [comment]
All goods. Just send through a PR of what you've got

**Comment by derogative404** [comment]
completed
