### ISSUE TITLE
Sizing and layouts for desktop and mobile 

### ISSUE THREAD

**Issue by inezchong7** [UoaWDCC/passport#53]
## Description

As a user
I want to see that the webapp's layout and sizing is optimized for both desktop and mobile environments
So that I can view information easily

## Acceptance Criteria

- [ ] Layout and sizing are tailored properly for mobile and desktop
- [ ] Error message if the webpage is tailored for desktop and not available for mobile view.

**Comment by derogative404** [comment]
duplicate
