### ISSUE TITLE
Styling and Design checking

### ISSUE THREAD

**Issue by inezchong7** [UoaWDCC/passport#54]
## Description

As a user
I want to see well-coordinated color schemes and design throughout the application.

## Acceptance Criteria

- [x] All colors used are consistent. (eg. no different shades of blue or yellow)
- [x] Every component is positioned and sized according to the Figma diagram for respective screens. 
- [ ] Improve any flaws in the user design if applicable.
- [x]  Layout and sizing are tailored properly for mobile and desktop
- [ ] Error message if the webpage is tailored for desktop and not available for mobile view.

**Comment by derogative404** [comment]
Complete
