### ISSUE TITLE
Super admin account

### ISSUE THREAD

**Issue by inezchong7** [UoaWDCC/passport#97]
## Description

As a WDCC executive
I want to access the admin dashboard
So that I can add/ edit events, view events and participants, check students off when they claim their prizes.

## Acceptance Criteria

- [x] super admin roles are added to the user schema
- [x] check account type during login for admin dashboard
- [x] only the admin accounts are allowed to access admin dashboard
- [x] all other accounts should be denied access and redirected to the home page.

**Comment by derogative404** [comment]
complete
